export const en = {
    "home_page_main_section_heading": "Discover the Perfect\n                                    <span>Service</span>\n                                    Instantly",
    "home_page_main_section_info": "Design that Speaks, Inspires, and Transforms",
    "home_page_search_placeholder": "Search",
    "home_page_services_mobile": "Mobile App",
    "home_page_services_web_app": "Web App and Software",
    "home_page_services_product": "Product",
    "home_page_services_graphic": "Graphic and Animations",
    "home_page_services_packaging": "Packaging and Branding",
    "home_services_subtitle": "Where Creativity Meets Demand",
    "home_services_title": "Our Masterpieces",
    "home_banner_subtitle": "Empower Your Creativity",
    "home_creativity_subtitle": "Empower Your Creativity",
    "home_creativity_title": "Unlock Your Design Potential",
    "home_creativity_description": "Immerse yourself in design with our expert-guided courses. Join a global community of 340+ designers, enhancing skills and mastering innovative techniques. Our customized courses are your stepping stones from passion to profession.\n                                    Let's create something amazing together.",
    "home_learn_more": "Learn More",
    "home_students": "Students over the world",
    "home_value_subtitle": "Value-Driven Excellence",
    "home_value_title": "Your Vision, Our Commitment",
    "home_budget_subtitle": "Budget-Friendly Brilliance",
    "home_budget_description": "Get premium services at prices that work for you. Our transparent, flat-rate pricing ensures quality that aligns with your financial plan.",
    "home_swift_title": "Swift & Stellar",
    "home_swift_description": "Match with skilled professionals in moments, not months. Expect enduring quality, delivered at the speed of thought.",
    "home_satisfaction_title": "Satisfaction Guaranteed",
    "home_satisfaction_description": "Enjoy peace of mind with our satisfaction-first policy. Payment is due only when you’re delighted — because your happiness is the true final draft.",
    "home_promise": "Our Promise, Your Peace of Mind",
    "home_resources_title": "Reliable Resources Round-the-Clock",
    "home_resources_description": "Day or night, our dedicated support team stands ready to assist. Wherever you are, we’re just a call or click away.",
    "get_in_touch_click": "Click to",
    "get_in_touch_contact": "Get in touch",
    "header_services": "Services",
    "header_learn": "Learn",
    "header_blog": "Blog",
    "header_meeting": "Book a Meeting",
    "header_about": "About Us",
    "header_contact": "Get in Touch",
    "header_lang_en": "English",
    "header_lang_es": "Spanish",
    "header_lang_de": "Deutsch",
    "header_lang_it": "Italian",
    "header_lang_fr": "French",
    "footer_branding": "Branding & Printing",
    "footer_ui_ux": "UI/UX Design",
    "footer_visual": "Visual Design",
    "footer_marketing": "Marketing Design",
    "footer_packaging": "Packaging & Covers",
    "footer_faq": "FAQ",
    "footer_privacy": "Privacy Policy",
    "footer_terms": "Terms and Conditions",
    "footer_rights": "© <span id=\"year\"></span >WowMoon All<br/>\n                            rights reserved",
    "services_title": "Our Expertise, Your Success",
    "services_description": "At WowMoons, we are dedicated to delivering excellence across a broad spectrum of\n                                services tailored to empower your business. Each offering is designed to meet the unique\n                                challenges and opportunities your business faces.",
    "services_all": "All Services"
};
export const de = {
    "home_page_main_section_heading": "Entdecken Sie sofort den perfekten\n                                    <span>Service</span>",
    "home_page_main_section_info": "Design, das spricht, inspiriert und verwandelt",
    "home_page_search_placeholder": "Suchen",
    "home_page_services_mobile": "Mobile App",
    "home_page_services_web_app": "Web App und Software",
    "home_page_services_product": "Produkt",
    "home_page_services_graphic": "Grafik und Animationen",
    "home_page_services_packaging": "Verpackung und Branding",
    "home_services_subtitle": "Wo Kreativität auf Nachfrage trifft",
    "home_services_title": "Unsere Meisterwerke",
    "home_banner_subtitle": "Stärken Sie Ihre Kreativität",
    "home_creativity_subtitle": "Stärken Sie Ihre Kreativität",
    "home_creativity_title": "Entfesseln Sie Ihr Designpotenzial",
    "home_creativity_description": "Tauchen Sie ein in das Design mit unseren von Experten geleiteten Kursen. Werden Sie Teil einer globalen Gemeinschaft von über 340 Designern, die Fähigkeiten verbessern und innovative Techniken meistern. Unsere maßgeschneiderten Kurse sind Ihre Sprungbretter von der Leidenschaft zum Beruf.\n                                    Lassen Sie uns gemeinsam etwas Erstaunliches erschaffen.",
    "home_learn_more": "Mehr erfahren",
    "home_students": "Studenten weltweit",
    "home_value_subtitle": "Wertorientierte Exzellenz",
    "home_value_title": "Ihre Vision, unser Engagement",
    "home_budget_subtitle": "Budgetfreundliche Brillanz",
    "home_budget_description": "Erhalten Sie erstklassige Dienstleistungen zu Preisen, die für Sie funktionieren. Unsere transparente, pauschale Preisgestaltung garantiert Qualität, die mit Ihrem Finanzplan übereinstimmt.",
    "home_swift_title": "Schnell und hervorragend",
    "home_swift_description": "Finden Sie in Momenten, nicht Monaten, erfahrene Fachleute. Erwarten Sie dauerhafte Qualität, geliefert mit der Geschwindigkeit des Gedankens.",
    "home_satisfaction_title": "Zufriedenheit garantiert",
    "home_satisfaction_description": "Genießen Sie Ruhe mit unserer Zufriedenheitsgarantie. Die Zahlung ist erst fällig, wenn Sie zufrieden sind – denn Ihre Zufriedenheit ist der wahre Endentwurf.",
    "home_promise": "Unser Versprechen, Ihre Ruhe",
    "home_resources_title": "Zuverlässige Ressourcen rund um die Uhr",
    "home_resources_description": "Tag und Nacht steht unser engagiertes Support-Team bereit, um zu helfen. Wo auch immer Sie sind, wir sind nur einen Anruf oder Klick entfernt.",
    "get_in_touch_click": "Klicken Sie, um",
    "get_in_touch_contact": "Kontakt aufzunehmen",
    "header_services": "Dienstleistungen",
    "header_learn": "Lernen",
    "header_blog": "Blog",
    "header_meeting": "Besprechung buchen",
    "header_about": "Über uns",
    "header_contact": "Kontakt aufnehmen",
    "header_lang_en": "Englisch",
    "header_lang_es": "Spanisch",
    "header_lang_de": "Deutsch",
    "header_lang_it": "Italienisch",
    "header_lang_fr": "Französisch",
    "footer_branding": "Branding & Druck",
    "footer_ui_ux": "UI/UX Design",
    "footer_visual": "Visuelles Design",
    "footer_marketing": "Marketing Design",
    "footer_packaging": "Verpackung & Cover",
    "footer_faq": "FAQ",
    "footer_privacy": "Datenschutzrichtlinie",
    "footer_terms": "Allgemeine Geschäftsbedingungen",
    "footer_rights": "© <span id=\"year\"></span >WowMoon Alle<br/>\\n                            Rechte vorbehalten",
    "services_title": "Unsere Expertise, Ihr Erfolg",
    "services_description": "Bei WowMoons sind wir darauf ausgerichtet, Exzellenz in einem breiten Spektrum von Dienstleistungen zu bieten, die darauf abgestimmt sind, Ihr Unternehmen zu stärken. Jedes Angebot ist darauf ausgerichtet, den einzigartigen Herausforderungen und Möglichkeiten, denen Ihr Unternehmen gegenübersteht, gerecht zu werden.",
    "services_all": "Alle Dienstleistungen"
};
export const it = {
    "home_page_main_section_heading": "Scopri il <span>Servizio</span> Perfetto\n                                    Istantaneamente",
    "home_page_main_section_info": "Design che Parla, Ispira e Trasforma",
    "home_page_search_placeholder": "Cerca",
    "home_page_services_mobile": "App Mobile",
    "home_page_services_web_app": "App Web e Software",
    "home_page_services_product": "Prodotto",
    "home_page_services_graphic": "Grafica e Animazioni",
    "home_page_services_packaging": "Packaging e Branding",
    "home_services_subtitle": "Dove la Creatività Incontra la Domanda",
    "home_services_title": "I Nostri Capolavori",
    "home_banner_subtitle": "Potenzia la Tua Creatività",
    "home_creativity_subtitle": "Potenzia la Tua Creatività",
    "home_creativity_title": "Sblocca il Tuo Potenziale di Design",
    "home_creativity_description": "Immergiti nel design con i nostri corsi guidati da esperti. Unisciti a una comunità globale di oltre 340 designer, migliorando le abilità e padroneggiando tecniche innovative. I nostri corsi personalizzati sono i tuoi gradini dal passione alla professione.\n                                    Creiamo insieme qualcosa di straordinario.",
    "home_learn_more": "Scopri di Più",
    "home_students": "Studenti in tutto il mondo",
    "home_value_subtitle": "Eccellenza Guidata dal Valore",
    "home_value_title": "La Tua Visione, Il Nostro Impegno",
    "home_budget_subtitle": "Brillantezza a Prezzi Accessibili",
    "home_budget_description": "Ottieni servizi premium a prezzi che funzionano per te. La nostra tariffazione piatta e trasparente assicura qualità che si allinea con il tuo piano finanziario.",
    "home_swift_title": "Rapido e Stellare",
    "home_swift_description": "Abbinati con professionisti qualificati in momenti, non mesi. Aspettati una qualità duratura, consegnata alla velocità del pensiero.",
    "home_satisfaction_title": "Soddisfazione Garantita",
    "home_satisfaction_description": "Goditi la tranquillità con la nostra politica basata sulla soddisfazione. Il pagamento è dovuto solo quando sei soddisfatto — perché la tua felicità è la vera bozza finale.",
    "home_promise": "La Nostra Promessa, La Tua Tranquillità",
    "home_resources_title": "Risorse Affidabili Disponibili Sempre",
    "home_resources_description": "Giorno e notte, il nostro team di supporto dedicato è pronto ad assisterti. Ovunque tu sia, siamo a solo una chiamata o un clic di distanza.",
    "get_in_touch_click": "Clicca per",
    "get_in_touch_contact": "Entrare in Contatto",
    "header_services": "Servizi",
    "header_learn": "Impara",
    "header_blog": "Blog",
    "header_meeting": "Prenota un Incontro",
    "header_about": "Chi Siamo",
    "header_contact": "Mettiti in Contatto",
    "header_lang_en": "Inglese",
    "header_lang_es": "Spagnolo",
    "header_lang_de": "Tedesco",
    "header_lang_it": "Italiano",
    "header_lang_fr": "Francese",
    "footer_branding": "Branding & Stampa",
    "footer_ui_ux": "Design UI/UX",
    "footer_visual": "Design Visuale",
    "footer_marketing": "Design di Marketing",
    "footer_packaging": "Packaging & Copertine",
    "footer_faq": "FAQ",
    "footer_privacy": "Politica sulla Privacy",
    "footer_terms": "Termini e Condizioni",
    "footer_rights": "© <span id=\"year\"></span> WowMoon Tutti i<br/>\n                            diritti riservati",
    "services_title": "La nostra competenza, il tuo successo",
    "services_description": "In WowMoons, siamo dedicati a fornire eccellenza attraverso un ampio spettro di servizi su misura per potenziare la tua azienda. Ogni offerta è progettata per affrontare le sfide e le opportunità uniche che la tua impresa incontra.",
    "services_all": "Tutti i servizi"
};
export const es = {
    "home_page_main_section_heading": "Descubre el <span>Servicio</span> Perfecto Instantáneamente",
    "home_page_main_section_info": "Diseño que Habla, Inspira y Transforma",
    "home_page_search_placeholder": "Buscar",
    "home_page_services_mobile": "App Móvil",
    "home_page_services_web_app": "App Web y Software",
    "home_page_services_product": "Producto",
    "home_page_services_graphic": "Gráficos y Animaciones",
    "home_page_services_packaging": "Empaquetado y Branding",
    "home_services_subtitle": "Donde la Creatividad Encuentra la Demanda",
    "home_services_title": "Nuestras Obras Maestras",
    "home_banner_subtitle": "Potencia Tu Creatividad",
    "home_creativity_subtitle": "Potencia Tu Creatividad",
    "home_creativity_title": "Desbloquea Tu Potencial de Diseño",
    "home_creativity_description": "Sumérgete en el diseño con nuestros cursos guiados por expertos. Únete a una comunidad global de más de 340 diseñadores, mejorando habilidades y dominando técnicas innovadoras. Nuestros cursos personalizados son tus peldaños desde la pasión hasta la profesión.\n                                    Creemos algo increíble juntos.",
    "home_learn_more": "Aprende Más",
    "home_students": "Estudiantes alrededor del mundo",
    "home_value_subtitle": "Excelencia Impulsada por el Valor",
    "home_value_title": "Tu Visión, Nuestro Compromiso",
    "home_budget_subtitle": "Brillantez Amigable con el Presupuesto",
    "home_budget_description": "Obtén servicios premium a precios que funcionan para ti. Nuestros precios fijos y transparentes garantizan calidad que se alinea con tu plan financiero.",
    "home_swift_title": "Rápido y Estelar",
    "home_swift_description": "Conecta con profesionales calificados en momentos, no meses. Espera calidad duradera, entregada a la velocidad del pensamiento.",
    "home_satisfaction_title": "Satisfacción Garantizada",
    "home_satisfaction_description": "Disfruta de tranquilidad con nuestra política de satisfacción primero. El pago solo se debe cuando estás encantado — porque tu felicidad es el verdadero borrador final.",
    "home_promise": "Nuestra Promesa, Tu Tranquilidad",
    "home_resources_title": "Recursos Fiables a Cualquier Hora",
    "home_resources_description": "Día o noche, nuestro equipo de soporte dedicado está listo para asistir. Dondequiera que estés, estamos a solo una llamada o un clic de distancia.",
    "get_in_touch_click": "Haz Clic para",
    "get_in_touch_contact": "Ponerse en Contacto",
    "header_services": "Servicios",
    "header_learn": "Aprender",
    "header_blog": "Blog",
    "header_meeting": "Reservar una Reunión",
    "header_about": "Sobre Nosotros",
    "header_contact": "Ponerse en Contacto",
    "header_lang_en": "Inglés",
    "header_lang_es": "Español",
    "header_lang_de": "Alemán",
    "header_lang_it": "Italiano",
    "header_lang_fr": "Francés",
    "footer_branding": "Branding e Impresión",
    "footer_ui_ux": "Diseño UI/UX",
    "footer_visual": "Diseño Visual",
    "footer_marketing": "Diseño de Marketing",
    "footer_packaging": "Embalaje y Cubiertas",
    "footer_faq": "FAQ",
    "footer_privacy": "Política de Privacidad",
    "footer_terms": "Términos y Condiciones",
    "footer_rights": "© <span id=\"year\"></span> WowMoon Todos los<br/>\n                            derechos reservados",
    "services_title": "Nuestra experiencia, tu éxito",
    "services_description": "En WowMoons, estamos dedicados a ofrecer excelencia a través de un amplio espectro de servicios diseñados para empoderar tu negocio. Cada servicio está diseñado para enfrentar los desafíos y oportunidades únicos que enfrenta tu empresa.",
    "services_all": "Todos los servicios"
};
export const fr = {
    "home_page_main_section_heading": "Découvrez le <span>Service</span> Parfait Instantanément",
    "home_page_main_section_info": "Un design qui Parle, Inspire et Transforme",
    "home_page_search_placeholder": "Rechercher",
    "home_page_services_mobile": "Application Mobile",
    "home_page_services_web_app": "Application Web et Logiciel",
    "home_page_services_product": "Produit",
    "home_page_services_graphic": "Graphiques et Animations",
    "home_page_services_packaging": "Emballage et Branding",
    "home_services_subtitle": "Là où la Créativité Rencontre la Demande",
    "home_services_title": "Nos Chefs-d'œuvre",
    "home_banner_subtitle": "Libérez Votre Créativité",
    "home_creativity_subtitle": "Libérez Votre Créativité",
    "home_creativity_title": "Débloquez Votre Potentiel de Conception",
    "home_creativity_description": "Plongez-vous dans le design avec nos cours guidés par des experts. Rejoignez une communauté mondiale de plus de 340 designers, améliorant vos compétences et maîtrisant des techniques innovantes. Nos cours personnalisés sont vos tremplins de la passion à la profession.\n                                    Créons ensemble quelque chose d'incroyable.",
    "home_learn_more": "En Savoir Plus",
    "home_students": "Étudiants du monde entier",
    "home_value_subtitle": "Excellence Pilotée par la Valeur",
    "home_value_title": "Votre Vision, Notre Engagement",
    "home_budget_subtitle": "Brillant et Économique",
    "home_budget_description": "Obtenez des services de première qualité à des prix qui vous conviennent. Notre tarification fixe et transparente assure une qualité qui correspond à votre plan financier.",
    "home_swift_title": "Rapide et Éclatant",
    "home_swift_description": "Rencontrez des professionnels qualifiés en quelques instants, et non en mois. Attendez-vous à une qualité durable, livrée à la vitesse de la pensée.",
    "home_satisfaction_title": "Satisfaction Garantie",
    "home_satisfaction_description": "Profitez de la tranquillité d'esprit avec notre politique de satisfaction prioritaire. Le paiement n'est dû que lorsque vous êtes enchanté — parce que votre bonheur est le véritable brouillon final.",
    "home_promise": "Notre Promesse, Votre Tranquillité d'Esprit",
    "home_resources_title": "Ressources Fiables Disponibles à Tout Moment",
    "home_resources_description": "Jour et nuit, notre équipe de support dédiée est prête à vous assister. Où que vous soyez, nous sommes juste à un appel ou un clic.",
    "get_in_touch_click": "Cliquez pour",
    "get_in_touch_contact": "Prendre Contact",
    "header_services": "Services",
    "header_learn": "Apprendre",
    "header_blog": "Blog",
    "header_meeting": "Réserver une Réunion",
    "header_about": "À Propos de Nous",
    "header_contact": "Prendre Contact",
    "header_lang_en": "Anglais",
    "header_lang_es": "Espagnol",
    "header_lang_de": "Allemand",
    "header_lang_it": "Italien",
    "header_lang_fr": "Français",
    "footer_branding": "Branding & Impression",
    "footer_ui_ux": "Design UI/UX",
    "footer_visual": "Design Visuel",
    "footer_marketing": "Design Marketing",
    "footer_packaging": "Emballage & Couvertures",
    "footer_faq": "FAQ",
    "footer_privacy": "Politique de Confidentialité",
    "footer_terms": "Conditions Générales",
    "footer_rights": "© <span id=\"year\"></span> WowMoon Tous<br/>\n                            droits réservés",
    "services_title": "Notre expertise, votre succès",
    "services_description": "Chez WowMoons, nous nous engageons à fournir l'excellence à travers un large spectre de services conçus pour renforcer votre entreprise. Chaque offre est conçue pour répondre aux défis et opportunités uniques auxquels votre entreprise est confrontée.",
    "services_all": "Tous les services"
};
